version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: whatsapp-ha:latest
    ports:
      - 3000:3000
    volumes:
      - .wwebjs_auth:/app/.wwebjs_auth
      - .env:/app/.env

  npm:
    image: whatsapp-ha:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm

  nodemon:
    image: whatsapp-ha:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: nodemon
    
