version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: whatsapp-ha:latest
    ports:
      - 3000:3000
    volumes:
      - .wwebjs_auth:/app/.wwebjs_auth
      - .env:/app/.env

  npm:
    image: node:14.16.0-buster-slim@sha256:ffc15488e56d99dbc9b90d496aaf47901c6a940c077bc542f675ae351e769a12
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: npm
    
